import json
from typing import Any

from ..graph.state import InvestigationState
from ..core.llm import gemini_chat_with_fallback


SYSTEM_PROMPT = """
You are a pharmaceutical incentive investigation analyst.

You receive structured anomaly findings generated by deterministic
analytics.

STRICT RULES:

1. Use ONLY facts present in the supplied evidence.
2. Never invent transactions, documents, policies, inventory records,
   patient-level data, delivery receipts, or compliance rules.
3. Never alter, recalculate, or reinterpret numeric values.
4. Never state that fraud, misconduct, manipulation, or abuse occurred.
5. An anomaly is only an indicator requiring human review.
6. Cross-territory sales are allowed in this business model.
7. Doctor ownership determines representative attribution.
8. Prescriptions are supporting anomaly evidence and do not determine
   incentive payout.
9. Recommendations must be directly supported by available evidence.
10. If evidence is insufficient for a conclusion, explicitly say so.

Return valid JSON only in this shape:

{
  "overall_assessment": "string",
  "key_findings": ["string"],
  "investigation_priorities": [
    {
      "priority": 1,
      "finding_type": "string",
      "reason": "string"
    }
  ],
  "recommended_next_action": "string"
}
"""


async def investigation_agent(
    state: InvestigationState,
) -> dict[str, Any]:

    investigation_data = {
        "representative_id": state["representative_id"],
        "product_id": state["product_id"],
        "month": state["month"],
        "overall_risk_score": state["overall_risk_score"],
        "overall_severity": state["overall_severity"],
        "findings": state["findings"],
    }

    prompt = f"""
{SYSTEM_PROMPT}

Review the following deterministic investigation evidence:

{json.dumps(investigation_data, indent=2)}

Return JSON only.
"""

    response_text = await gemini_chat_with_fallback(
        prompt
    )

    try:
        parsed = json.loads(response_text)

    except json.JSONDecodeError:
        parsed = {
            "overall_assessment": response_text,
            "key_findings": [],
            "investigation_priorities": [],
            "recommended_next_action": (
                "AI response could not be parsed as JSON."
            ),
        }

    return {
        "investigation_summary": parsed
    }
